title: <p align="center"> Buu NGUYEN </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume.pdf">Résumé</a> |
  <a href="https://www.linkedin.com/in/buu-nguyen/">LinkedIn</a> |
  <a href="https://github.com/buu-nguyen">GitHub</a>
  </p>
  
  <p align="center">
  Fresher - Majored in Data Science
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-230766534-1 # Google Analytics tracking ID
