title: <p align="center"> Buu NGUYEN </p>

#logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/buu-nguyen/">LinkedIn</a> |
  <a href="https://github.com/buu-nguyen">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Data Science at CY Tech - CY Cergy Paris Université.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
